package: simplestats
version: '1.0.0'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/simplestats

page:
    title: 'Simple-Stats'
    pjax: false
    hasLayout: false
    icon: rex-icon rex-icon-seo
    linkAttr: { target: _blank }
